# docker compose up --build
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    #depends_on:
    #  - backend
    volumes:
      - ./frontend/src:/app/src

# TODO: switch from postgres to oracle

  # backend:
  #   build: ./backend
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - DATABASE_URL=postgres://user:password@database:5432/tododb
  #   depends_on:
  #     - database

  # database:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: tododb
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - db_data:/var/lib/postgresql/data