# docker compose up --build
services:
  frontend:
    build: ./frontend
    ports:
<<<<<<< HEAD
      - "5173:3000" #host:container (must go to host port 5173)
    volumes:
      - ./frontend/src:/app/src # can have all in app src (frontend backend etc.)
    # depends_on:
    #   - backend

  # backend:
  #   build: ./backend
  #   ports:
  #     - "5000:5000"
  #   # volumes: 
  #   #   - ./backend:/app
  #   environment:
  #     - DATABASE_URL=postgres://user:password@database:5432/tododb
  #   depends_on:
  #     - database

  # database:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: tododb
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
=======
      - "3000:5173"
    #depends_on:
    #  - backend
    volumes:
      - ./frontend/src:/app/src
>>>>>>> 5c4f7ec4c6df4bb61049bb288822e2c88d5a6acd

  # backend:
  #   build: ./backend
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - DATABASE_URL=postgres://user:password@database:5432/tododb
  #   depends_on:
  #     - database

  # database:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: tododb
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - db_data:/var/lib/postgresql/data